// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGnHVsxiG_kuFd-T459__jXyyMmBU4-S4',
    appId: '1:345802264552:web:dcdd633bb5fd3f2a029e5d',
    messagingSenderId: '345802264552',
    projectId: 'medical-portal-b8a02',
    authDomain: 'medical-portal-b8a02.firebaseapp.com',
    storageBucket: 'medical-portal-b8a02.appspot.com',
    measurementId: 'G-JR2PMJ3J40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr8Jizgy1nl0quXX_YhdANoT-bR9-3GuI',
    appId: '1:345802264552:android:2322dbe49a60ca1c029e5d',
    messagingSenderId: '345802264552',
    projectId: 'medical-portal-b8a02',
    storageBucket: 'medical-portal-b8a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5N8MBypfkrOOFMnNzGPZBRXNYQZCSzbo',
    appId: '1:345802264552:ios:b22b05a1094e9792029e5d',
    messagingSenderId: '345802264552',
    projectId: 'medical-portal-b8a02',
    storageBucket: 'medical-portal-b8a02.appspot.com',
    iosClientId: '345802264552-m3arnf8lmbjlit7o330brdgmq78a5b6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5N8MBypfkrOOFMnNzGPZBRXNYQZCSzbo',
    appId: '1:345802264552:ios:b22b05a1094e9792029e5d',
    messagingSenderId: '345802264552',
    projectId: 'medical-portal-b8a02',
    storageBucket: 'medical-portal-b8a02.appspot.com',
    iosClientId: '345802264552-m3arnf8lmbjlit7o330brdgmq78a5b6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalPortal',
  );
}
